[tools]
java = "openjdk"
python = "3"

[tasks.cache]
description = "Grab the cache"
run = """
#!/usr/bin/env bash
wget https://github.com/abextm/osrs-cache/releases/download/2024-12-04-rev227/dump-2024-12-04-rev227.tar.gz
tar -xzvf dump-2024-12-04-rev227.tar.gz -C data/cache --strip-components=1
rm dump-2024-12-04-rev227.tar.gz
"""
